# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  api:
    image: personal-blog-api
    container_name: personal-blog-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MONGODB_DB_USER: ${MONGODB_DB_USER}
      MONGODB_DB_PASS: ${MONGODB_DB_PASS}
      UPLOAD_FOLDER_PATH: ${UPLOAD_FOLDER_PATH}
      API_PREFIX: ${API_PREFIX}
      API_SWAGGER_URL: ${API_SWAGGER_URL}
      API_PORT: ${API_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_DB_PASS}

volumes:
  mongodata:
