name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 stop personal-blog
            cd /var/www/personal-blog-app
            git pull origin master
            npm install --prefix /var/www/personal-blog-app/api
            npm install --prefix /var/www/personal-blog-app/app
            pm2 restart personal-blog
